name: flutter_slidable_plus_plus
description: A Flutter implementation of slidable list item with directional slide actions that can be dismissed, forked from flutter_slidable_plus.
version: 0.1.0

homepage: https://github.com/NetServe-Innovations/flutter_slidable_plus_plus

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  collection:

flutter:
  uses-material-design: true
